version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  
workflows:
    example-workflow:
      jobs:
        - cypress/install:
            install-command: npm install
#         - cypress/install:
#             install-command: yarn install --frozen-lockfile 
        - cypress/run:
            requires:
              - cypress/install
            record: true
            parallel: true
            parallelism: 1
