version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0

workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
            - run: 
                when: always
                name: Merge MochaAwesome Reports
                command: npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json 
            - run: 
                when: always
                name: Create mochawesome html report
                command: npx marge mochareports/*.json -f report -o mochareports
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/reports/tests
          
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - add-cypress
    jobs:
      - cypress/run:
          post-steps:
            - run: 
                when: always
                name: Merge MochaAwesome Reports
                command: npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json 
            - run: 
                when: always
                name: Create mochawesome html report
                command: npx marge mochareports/*.json -f report -o mochareports
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/reports/tests
         
